# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/148MswCOsvo9i3hqCBEP5Z2Lb9Ce0k_Bm
"""

from abc import ABC, abstractmethod


class Coffee(ABC):

    @abstractmethod
    def prepare(self):
        pass


class BaseCoffee(Coffee):

    def __init__(self):
        self.__water = 100
        self.__milk = 50
        self.__coffee = 20

    def get_water(self):
        return self.__water

    def get_milk(self):
        return self.__milk

    def get_coffee(self):
        return self.__coffee

    def ingredients(self, sugar=0, extra_shot=False):

        print(f"Water: {self.__water}ml")
        print(f"Milk: {self.__milk}ml")
        print(f"Coffee: {self.__coffee}g")
        print(f"Sugar: {sugar} tsp")

        if extra_shot:
            print("Extra coffee shot added")


class Espresso(BaseCoffee):

    def prepare(self):
        print("\nPreparing Espresso")
        self.ingredients()
        print("Espresso Ready")


class Americano(Espresso):

    def prepare(self):
        print("\nPreparing Americano")
        self.ingredients(sugar=1)
        print("Adding extra hot water")
        print("Americano Ready")


class Latte(Americano):

    def prepare(self):
        print("\nPreparing Latte")
        self.ingredients(sugar=2)
        print("Adding steamed milk")
        print("Latte Ready")


class Cappuccino(Latte):

    def prepare(self):
        print("\nPreparing Cappuccino")
        self.ingredients(sugar=2, extra_shot=True)
        print("Adding milk foam")
        print("Cappuccino Ready")


class CoffeeMachine:

    def make_coffee(self, coffee):
        coffee.prepare()


machine = CoffeeMachine()

espresso = Espresso()
americano = Americano()
latte = Latte()
cappuccino = Cappuccino()

machine.make_coffee(espresso)
machine.make_coffee(americano)
machine.make_coffee(latte)
machine.make_coffee(cappuccino)