# -*- coding: utf-8 -*-
"""numpy  project2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RJXsd8H1qNw-Z8btFZHmw96t3IB5w6bI
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from google.colab import files

uploaded = files.upload()

image_path = "photo.jpg"

image = mpimg.imread(image_path)

if image.max() <= 1.0:
    image = image * 255

image = image.astype(np.uint8)

print("ORIGINAL IMAGE DETAILS")
print("Image Shape :", image.shape)
print("Data Type   :", image.dtype)

grayscale = np.dot(
    image[:, :, :3],
    [0.2989, 0.5870, 0.1140]
)

grayscale = grayscale.astype(np.uint8)
print("GRAYSCALE IMAGE DETAILS")
print("Grayscale Shape :", grayscale.shape)

bright_image = np.clip(
    grayscale.astype(int) + 50,
    0,
    255
).astype(np.uint8)

dark_image = np.clip(
    grayscale.astype(int) - 50,
    0,
    255
).astype(np.uint8)

horizontal_flip = np.fliplr(grayscale)

vertical_flip = np.flipud(grayscale)

rotated_image = np.rot90(grayscale)

height, width = grayscale.shape

cropped_image = grayscale[
    height // 4 : 3 * height // 4,
    width // 4 : 3 * width // 4
]

blurred_image = grayscale.copy()

for i in range(1, grayscale.shape[0] - 1):
    for j in range(1, grayscale.shape[1] - 1):

        blurred_image[i, j] = np.mean(
            grayscale[i-1:i+2, j-1:j+2]
        )

blurred_image = blurred_image.astype(np.uint8)

fig, axes = plt.subplots(2, 5, figsize=(22, 10))

plt.suptitle(
    "Grayscale Image Manipulator Project",
    fontsize=20,
    fontweight="bold"
)
axes[0, 0].imshow(image)
axes[0, 0].set_title("Original")
axes[0, 0].axis("off")
axes[0, 1].imshow(grayscale, cmap="gray")
axes[0, 1].set_title("Grayscale")
axes[0, 1].axis("off")

axes[0, 2].imshow(bright_image, cmap="gray")
axes[0, 2].set_title("Bright")
axes[0, 2].axis("off")

axes[0, 3].imshow(dark_image, cmap="gray")
axes[0, 3].set_title("Dark")
axes[0, 3].axis("off")

axes[0, 4].imshow(rotated_image, cmap="gray")
axes[0, 4].set_title("Rotated")
axes[0, 4].axis("off")

axes[1, 0].imshow(horizontal_flip, cmap="gray")
axes[1, 0].set_title("Horizontal Flip")
axes[1, 0].axis("off")

axes[1, 1].imshow(vertical_flip, cmap="gray")
axes[1, 1].set_title("Vertical Flip")
axes[1, 1].axis("off")

axes[1, 2].imshow(cropped_image, cmap="gray")
axes[1, 2].set_title("Cropped")
axes[1, 2].axis("off")
axes[1, 3].imshow(blurred_image, cmap="gray")
axes[1, 3].set_title("Blurred")
axes[1, 3].axis("off")

axes[1, 4].hist(
    grayscale.ravel(),
    bins=50
)

axes[1, 4].set_title("Histogram")
axes[1, 4].set_xlabel("Pixel Value")
axes[1, 4].set_ylabel("Frequency")

plt.tight_layout()
plt.show()

print("\n===================================")
print("PROJECT COMPLETED SUCCESSFULLY")
print("===================================")