# -*- coding: utf-8 -*-
"""pandas project 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16V6ng9tHEMQkSx9yDZUJGd2eZgC3YE3c
"""

!pip install kagglehub -q

# Import library
import kagglehub

# STEP 2: DOWNLOAD IPL DATASET
path = kagglehub.dataset_download("manasgarg/ipl")

print("===================================")
print("DATASET DOWNLOADED SUCCESSFULLY")
print("===================================")

print("Dataset Path:")
print(path)

import pandas as pd
import numpy as np

file_path = "/root/.cache/kagglehub/datasets/manasgarg/ipl/versions/5/matches.csv"

# Load dataset
df = pd.read_csv(file_path)

print("===================================")
print("IPL DATASET LOADED SUCCESSFULLY")
print("===================================")

print("\n===================================")
print("FIRST 5 ROWS")
print("===================================")

print(df.head())

print("\n===================================")
print("DATASET SHAPE")
print("===================================")

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print("\n===================================")
print("COLUMN NAMES")
print("===================================")

print(df.columns)

print("\n===================================")
print("DATASET INFORMATION")
print("===================================")

print(df.info())

print("\n===================================")
print("STATISTICAL SUMMARY")
print("===================================")

print(df.describe(include='all'))

print("\n===================================")
print("MATCHES PLAYED EACH SEASON")
print("===================================")

matches_per_season = (
    df['season']
    .value_counts()
    .sort_index()
)

print(matches_per_season)

print("\n===================================")
print("TEAM WITH MOST WINS")
print("===================================")

team_wins = df['winner'].value_counts()

print(team_wins)

most_successful_team = team_wins.idxmax()
most_wins = team_wins.max()

print(f"\nMost Successful Team : {most_successful_team}")
print(f"Total Wins           : {most_wins}")

print("\n===================================")
print("AVAILABLE VENUES")
print("===================================")

venues = df['venue'].unique()

for venue in venues:
    print(venue)

venue_name = "Wankhede Stadium"

venue_matches = df[df['venue'] == venue_name]

print("\n===================================")
print(f"MATCHES PLAYED AT {venue_name.upper()}")
print("===================================")

print(
    venue_matches[
        [
            'season',
            'team1',
            'team2',
            'winner',
            'venue'
        ]
    ]
)

print(f"\nTotal Matches at {venue_name}: {len(venue_matches)}")

print("\n===================================")
print("TOP 5 PLAYER OF THE MATCH WINNERS")
print("===================================")

top_players = (
    df['player_of_match']
    .value_counts()
    .head(5)
)

print(top_players)

print("\n===================================")
print("NULL VALUES IN DATASET")
print("===================================")

null_values = df.isnull().sum()

print(null_values)

print("\n===================================")
print("HANDLING MISSING VALUES")
print("=====================================")
df = df.drop(columns=['umpire3'])
print("Dropped Column: umpire3")


clean_df = df.dropna(
    subset=[
        'winner',
        'player_of_match',
        'city'
    ]
)

print("\nDataset Cleaned Successfully")

print(f"\nOriginal Shape : {df.shape}")
print(f"Cleaned Shape  : {clean_df.shape}")

print("\n===================================")
print("TEAMS SORTED BY TOTAL WINS")
print("===================================")

sorted_team_wins = (
    clean_df['winner']
    .value_counts()
    .sort_values(ascending=False)
)

print(sorted_team_wins)

print("\n===================================")
print("MATCHES WON BY MUMBAI INDIANS")
print("===================================")

mi_matches = clean_df[
    clean_df['winner'] == 'Mumbai Indians'
]

print(
    mi_matches[
        [
            'season',
            'team1',
            'team2',
            'winner'
        ]
    ].head(10)
)

print("\n===================================")
print("AVERAGE WIN BY RUNS EACH SEASON")
print("===================================")

average_runs = (
    clean_df
    .groupby('season')['win_by_runs']
    .mean()
)

print(average_runs)

print("\n===================================")
print("WIN PERCENTAGE ANALYSIS")
print("===================================")

batting_first = clean_df[
    clean_df['win_by_runs'] > 0
]

batting_first_wins = (
    batting_first['winner']
    .value_counts()
)

fielding_first = clean_df[
    clean_df['win_by_wickets'] > 0
]

fielding_first_wins = (
    fielding_first['winner']
    .value_counts()
)
total_wins = (
    clean_df['winner']
    .value_counts()
)
batting_first_percentage = (
    batting_first_wins
    /
    total_wins
) * 100

fielding_first_percentage = (
    fielding_first_wins
    /
    total_wins
) * 100


batting_first_percentage = (
    batting_first_percentage
    .fillna(0)
    .round(2)
)

fielding_first_percentage = (
    fielding_first_percentage
    .fillna(0)
    .round(2)
)
print("\n-----------------------------------")
print("WIN % WHEN BATTING FIRST")
print("-----------------------------------")

print(
    batting_first_percentage
    .sort_values(ascending=False)
)

print("\n-----------------------------------")
print("WIN % WHEN FIELDING FIRST")
print("-----------------------------------")

print(
    fielding_first_percentage
    .sort_values(ascending=False)
)

print("\n===================================")
print("TOP 10 MOST SUCCESSFUL TEAMS")
print("===================================")

print(sorted_team_wins.head(10))

print("\n===================================")
print("MOST COMMON PLAYER OF THE MATCH")
print("===================================")

best_player = (
    clean_df['player_of_match']
    .value_counts()
    .idxmax()
)

best_player_awards = (
    clean_df['player_of_match']
    .value_counts()
    .max()
)

print(f"Player : {best_player}")
print(f"Awards : {best_player_awards}")

print("\n===================================")
print("PROJECT SUMMARY")
print("===================================")

print(f"Total Matches Analysed : {len(clean_df)}")
print(f"Total Seasons          : {clean_df['season'].nunique()}")
print(f"Total Teams            : {len(clean_df['winner'].unique())}")
print(f"Most Successful Team   : {most_successful_team}")

# PROJECT COMPLETED
print("\n===================================")
print("IPL DATA ANALYSIS COMPLETED")
print("===================================")