# -*- coding: utf-8 -*-
"""pandas project 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1Ew3gEkduUYWplfQ40eBLjGprN-r_l1
"""

!pip install kagglehub -q
import kagglehub

# STEP 2: DOWNLOAD DATASET
path = kagglehub.dataset_download(
    "vivek468/superstore-dataset-final"
)

print("===================================")
print("DATASET DOWNLOADED SUCCESSFULLY")
print("===================================")

print("Dataset Path:")
print(path)

import pandas as pd
import numpy as np
file_path = "/kaggle/input/superstore-dataset-final/Sample - Superstore.csv"

df = pd.read_csv(file_path, encoding='latin1')
print("===================================")
print("DATASET LOADED SUCCESSFULLY")
print("===================================")

print("\n===================================")
print("FIRST 5 ROWS")
print("===================================")

print(df.head())

print("\n===================================")
print("DATASET SHAPE")
print("===================================")

print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

print("\n===================================")
print("COLUMN NAMES")
print("===================================")

print(df.columns)

print("\n===================================")
print("DATASET INFORMATION")
print("===================================")

print(df.info())

print("\n===================================")
print("STATISTICAL SUMMARY")
print("===================================")

print(df.describe(include='all'))

print("\n===================================")
print("NULL VALUES IN DATASET")
print("===================================")

print(df.isnull().sum())
df = df.dropna()

print("\nDataset cleaned successfully!")

df['Order Date'] = pd.to_datetime(
    df['Order Date']
)

print("\n===================================")
print("ORDER DATE CONVERTED TO DATETIME")
print("===================================")

print(df['Order Date'].head())

print("\n===================================")
print("TOTAL SALES & PROFIT")
print("BY REGION AND CATEGORY")
print("===================================")

sales_profit = (
    df.groupby(
        ['Region', 'Category']
    )
    .agg({
        'Sales': ['sum', 'mean'],
        'Profit': ['sum', 'mean']
    })
    .round(2)
)

print(sales_profit)

print("\n===================================")
print("TOP 3 SUB-CATEGORIES IN EACH REGION")
print("===================================")

subcategory_sales = (
    df.groupby(
        ['Region', 'Sub-Category']
    )['Sales']
    .sum()
    .reset_index()
)

top_subcategories = (
    subcategory_sales
    .sort_values(
        ['Region', 'Sales'],
        ascending=[True, False]
    )
    .groupby('Region')
    .head(3)
)

print(top_subcategories)

print("\n===================================")
print("PROFIT MARGIN CALCULATION")
print("===================================")

# Formula:
# Profit Margin % = (Profit / Sales) * 100

df['Profit Margin %'] = (
    (df['Profit'] / df['Sales']) * 100
)

# Round values
df['Profit Margin %'] = (
    df['Profit Margin %']
    .round(2)
)

print(
    df[
        [
            'Sales',
            'Profit',
            'Profit Margin %'
        ]
    ].head()
)

print("\n===================================")
print("CUSTOM SALES CATEGORY")
print("===================================")

df['Sales Category'] = df['Sales'].apply(
    lambda x:
        'High' if x > 500
        else 'Medium' if x > 200
        else 'Low'
)

print(
    df[
        [
            'Sales',
            'Sales Category'
        ]
    ].head(10)
)

print("\n===================================")
print("PIVOT TABLE")
print("AVERAGE SALES BY REGION & SEGMENT")
print("===================================")

pivot_table = pd.pivot_table(
    df,
    values='Sales',
    index='Region',
    columns='Segment',
    aggfunc='mean'
).round(2)

print(pivot_table)

print("\n===================================")
print("MONTHS WITH NEGATIVE TOTAL PROFIT")
print("===================================")


df['Month-Year'] = (
    df['Order Date']
    .dt.to_period('M')
)

monthly_profit = (
    df.groupby('Month-Year')['Profit']
    .sum()
)

negative_profit_months = (
    monthly_profit[
        monthly_profit < 0
    ]
)

print(negative_profit_months)

print("\n===================================")
print("QUARTERLY SALES TREND")
print("===================================")

quarterly_sales = (
    df
    .set_index('Order Date')
    .resample('Q')['Sales']
    .sum()
)

print(quarterly_sales)

print("\n===================================")
print("ADVANCED GROUPBY ANALYSIS")
print("===================================")

advanced_analysis = (
    df.groupby('Region')
    .agg({
        'Sales': ['sum', 'mean', 'max'],
        'Profit': ['sum', 'mean', 'min']
    })
    .round(2)
)
print(advanced_analysis)

print("\n===================================")
print("TOP 10 MOST PROFITABLE PRODUCTS")
print("===================================")

top_products = (
    df.groupby('Product Name')['Profit']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_products)

print("\n===================================")
print("REGION-WISE TOTAL SALES")
print("===================================")

region_sales = (
    df.groupby('Region')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(region_sales)

print("\n===================================")
print("CATEGORY-WISE TOTAL PROFIT")
print("===================================")

category_profit = (
    df.groupby('Category')['Profit']
    .sum()
    .sort_values(ascending=False)
)

print(category_profit)

print("\n===================================")
print("SEGMENT-WISE TOTAL SALES")
print("===================================")

segment_sales = (
    df.groupby('Segment')['Sales']
    .sum()
    .sort_values(ascending=False)
)

print(segment_sales)

print("\n===================================")
print("MOST PROFITABLE REGION")
print("===================================")

region_profit = (
    df.groupby('Region')['Profit']
    .sum()
)

best_region = region_profit.idxmax()
best_profit = region_profit.max()

print(f"Best Region : {best_region}")
print(f"Total Profit: {best_profit:.2f}")

print("\n===================================")
print("PROJECT SUMMARY")
print("===================================")

print(f"Total Orders          : {len(df)}")
print(f"Total Regions         : {df['Region'].nunique()}")
print(f"Total Categories      : {df['Category'].nunique()}")
print(f"Total Sub-Categories  : {df['Sub-Category'].nunique()}")
print(f"Total Sales           : {df['Sales'].sum():,.2f}")
print(f"Total Profit          : {df['Profit'].sum():,.2f}")

# PROJECT COMPLETED
print("\n===================================")
print("SALES PERFORMANCE ANALYSIS COMPLETED")
print("===================================")