# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GtsAsHXcdOyJ5OXnMASPb3M1mqnPBUw-
"""

print(type("hello world"))

a=2
b=3
print(a+b)
print(type(a+b))

for i in range(1,11):
  print(i)

n=5
for i in range(1,11):
  print(n*i)

a=input()
b=input()

print(a+b)

a=int(input())
b=int(input())
print(a+b)

import math
for num in range(2,101):
  is_prime = True
  for i in range(2,int(math.sqrt(num))+1):
    if num % i == 0:
      is_prime=False
      break
  if is_prime:
    print(num,end=" ")

def hello(name):
  print(f"hello,{name}!")
  hello("raj")

list=["hello","world",1,6]
print(list)

a=[21,2,3,5,11]
square=[x**2 for x in a]
print("square",square)

a=["cat","dog","monkey","cow","deer"]
for i in list:
  print(i.upper())

a=["cat","dog","monkey","cow","deer"]
for idx,animal in enumerate(a,start=0):
  print(f"{idx}.{animal}")

l=["riya","kungun","kriti","sidharth","aman","roshan","saif","roshni"]
print(l[2:5:1])

l=["riya","kungun","kriti","sidharth","aman","roshan","saif","roshni"]
print(l[:8:-2])

a=int(input("enter the first number:"))
b=int(input("enter the second number:"))

def num(a,b):
  if(a+b==5):
    list=[1,2,3,4,5]
    print(list)
  elif(a+b>5):
    set={1,2,3,4,5}
    print(set)
  else:
      list1=[i*a for i in range(1,6)]
      list2=[i*b for i in range(1,6)]
      list3=[list1,list2]
      print(list3)

num(a,b)

class car:
  def __init__(self,brand,color,mileage):
    self.brand=brand
    self.color=color
    self.mileage=mileage

  def mileage_type(self):
    if self.mileage>=90:
      return "high mileage"
    elif self.mileage<75:
      return "medium mileage"
    else:
      return "low mileage"
  def __repr__(self):
         return f"car(brand='{self.brand}',color='{self.color}',mileage={self.mileage})"
s1=car("defender","black",90)
s2=car("bmw","white",75)
print(s1.mileage_type())
print(s2.mileage_type())
print(s1)
print(s2)

from abc import ABC, abstractmethod
# Abstract Class
class Car(ABC):
    def __init__(self, color, mileage):
        # Encapsulation
        self.__color = color
        self.__mileage = mileage
    # Getter methods
    def get_color(self):
        return self.__color
    def get_mileage(self):
        return self.__mileage
    # Abstract method (Polymorphism)
    @abstractmethod
    def get_info(self):
        pass
# Inheritance
class Tesla(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Tesla Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class BMW(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"BMW Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
class Audi(Car):
    # Polymorphism - own implementation
    def get_info(self):
        return f"Audi Car of Color: {self.get_color()}, Mileage: {self.get_mileage()} km"
# Objects
car1 = Tesla("Red", 500)
car2 = BMW("Black", 400)
car3 = Audi("White", 450)

# Polymorphism - same method name, different implementations
cars = [car1, car2, car3]
for car in cars:
    print(car.get_info())

list=("hello",24,155.5,"true","mango",80,50.7,"hii")
print(type(list))

l1=["hii"]
print(l1)
l2=["hii","hello","hey","billi","good"]
print(l2)
l3=l1+l2
print(l3)

l1=[1]
l2=[2,3,4,5,6]
l3=[l1,l2]
print(l3[1][3])

import numpy as np
np.array=([1,2,3,4,5,6,7,8,9,10])
print(np.array[1:6])
print(np.array[1:6:2])
print(np.array[ :6])
print(np.array[1: ])
print(np.array[ ::-1])

import numpy as np
np.array1=([1,2])
np.array2=([3,4,5,6,7,8,9,0])
np.array=[np.array1,np.array2]
print(np.array[1:6])
print(np.array[1:6:2])
print(np.array[ :6])
print(np.array[1: ])
print(np.array[ ::-1])

import numpy as np
np.array1=([1,2])
np.array2=([3,4,5])
np.array3=([6,7,8,9,10])
np.array=[np.array1,np.array2,np.array3]
print(np.array[1:6])
print(np.array[1:6:2])
print(np.array[ :6])
print(np.array[1: ])
print(np.array[ ::-1])

import numpy as np


v1 = np.array([1,2,3,4,5,6,7,8,9,10])

print(v1[v1>5])
print(v1+5)
print(v1*2)
print(v1[1:5])
print(v1[ ::-1])
print(v1[0:5:-1])

print("hello world")

import numpy as np
s=[[1,2,3],[3,4,5],[5,6,7]]
s1=np.array(s)
print(s1[1])
print(s1[2])
print(s1[-1])
print(s1[1][1])
print(s1[1][-1])
print(s1[-1][-2])
print(s1[1][0])
s1[0][0]=12
s2=(s1+s1)
print(s2)
print([[s1],[s1]])